name: Terraform Deploy

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./terraform

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az login -u ${{secrets.AZ_USERNAME}} -p ${{secrets.AZ_PASSWORD}}
            az account show

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
      - run: echo ${{ steps.plan.outputs.stdout }}
      - run: echo ${{ steps.plan.outputs.stderr }}
      - run: echo ${{ steps.plan.outputs.exitcode }}

      - name: Terraform Apply
        #if: ${{ github.event_name == 'push' }}
        run: terraform apply --auto-approve
